acseo_typesense:
    # Typesense host settings
    typesense:
        url: '%env(resolve:TYPESENSE_URL)%'
        key: '%env(resolve:TYPESENSE_KEY)%'

    # Collection settings
    collections:
        data:
            entity: 'App\Entity\Data'                   # Doctrine Entity class
            fields:
                id:                                     # Entity attribute name
                    name: id                            # Typesense attribute name
                    type: primary                       # Attribute type
                sortable_id:
                    entity_attribute: id                # Entity attribute name forced
                    name: sortable_id                   # Typesense field name
                    type: int32
                title:
                    name: title
                    type: string
                content:
                    name: content
                    type: string
                words:
                    name: words
                    type: string
            default_sorting_field: sortable_id          # Default sorting field. Must be int32 or float